"""Shopee 适配器 —— Open Platform v2 `get_order_detail` 查单。

## 出处

本文件每一处平台细节都来自 Shopee Open Platform 的 API 文档（2026-09-23 核对）。
文档站 `open.shopee.cn` 是 JS 单页应用，正文取自文档站自己调用的数据接口：

- 查单：v2.order.get_order_detail
  https://open.shopee.cn/opservice/api/v1/doc/api/?version=2&api_name=v2.order.get_order_detail
- 状态枚举：v2.order.get_order_list 的 order_status
  https://open.shopee.cn/opservice/api/v1/doc/api/?version=2&api_name=v2.order.get_order_list

## 签名

`get_order_detail` 公共参数 `sign` 的原文：「Signature generated by partner_id, api path,
timestamp, access_token, shop_id and partner_key via HMAC-SHA256」。签名串按这个顺序
**直接拼接、不加分隔符**，HMAC key 是 partner_key，输出小写十六进制（v2.public.get_access_token
文档请求样例里的 `sign` 是 64 位小写十六进制）。「不加分隔符」这一点 API 页没有明写 —— 讲签名
细节的开发者指南页读不到正文，见 `docs/DECISIONS.md` 的 `## task-t165`。

## 本轨没有 Push 验签

Shopee 的推送（Push Mechanism，订单状态更新是 code 3）的签名规则写在开发者指南里，
本轮读不到正文，按派单「核不到不许凭记忆写」没有实现 verifier、也没有登记。
凭据到位、文档核实之后另开一轨补。

## 凭据只在调用时读

导入本模块、实例化适配器都不读任何环境变量（同 `tiktok_shop.py` 模块头）。
"""

from __future__ import annotations

import hashlib
import hmac
import json
import time
import urllib.parse
from typing import Callable

from maos.tools.commerce import (
    CommerceAdapter, CommerceError, HttpResponse, QueryRequest, RawOrder, StatusRule,
    read_credential,
)


PLATFORM = "shopee"

#: get_order_detail 文档的 url 字段。
API_HOST = "https://partner.shopeemobile.com"
ORDER_DETAIL_PATH = "/api/v2/order/get_order_detail"

_DOC_DETAIL = ("https://open.shopee.cn/opservice/api/v1/doc/api/"
               "?version=2&api_name=v2.order.get_order_detail")
_DOC_LIST = ("https://open.shopee.cn/opservice/api/v1/doc/api/"
             "?version=2&api_name=v2.order.get_order_list")


def _enum_source(value: str) -> str:
    return (f"Shopee Open Platform v2.order.get_order_list / order_status 枚举 {value}"
            f"（UNPAID/READY_TO_SHIP/PROCESSED/SHIPPED/COMPLETED/IN_CANCEL/CANCELLED/"
            f"INVOICE_PENDING）/ {_DOC_LIST}；字段见 v2.order.get_order_detail / "
            f"response.order_list[].order_status / {_DOC_DETAIL}")


#: 状态归一表。field 是 get_order_detail 响应里订单对象的 `order_status`。
#:
#: Shopee 文档只列了枚举名，**没有给每个值的含义**，所以只收名字本身就说清了的：
#: `CANCELLED`、`SHIPPED`，外加 `COMPLETED`（超出字面，理由见 DECISIONS）。
#: 有意不进表：`UNPAID`（没付款）；`READY_TO_SHIP` / `PROCESSED`（货到付款的单在这两态
#: 也还没付钱，归 paid 会把 COD 单说成已付款）；`IN_CANCEL`（取消申请中，契约 §C.1 说的
#: 最不该往下走的那类）；`INVOICE_PENDING` / `PENDING`（文档没给含义）。它们走
#: `UnmappedOrderStatus`，那是设计。
_RULES = (
    StatusRule("order_status", ("cancelled",), "cancelled", source=_enum_source("CANCELLED")),
    StatusRule("order_status", ("shipped",), "shipped", source=_enum_source("SHIPPED")),
    StatusRule("order_status", ("completed",), "shipped", source=_enum_source("COMPLETED")),
)


# ---- 签名：两个纯函数，各自可单测 ------------------------------------------------

def sign_base_string(partner_id: str, path: str, timestamp: str, access_token: str,
                     shop_id: str) -> str:
    """shop 级接口的签名串：`partner_id + api path + timestamp + access_token + shop_id`。

    顺序照 `sign` 参数说明原文的列举顺序，直接拼接、不加分隔符。
    """
    return f"{partner_id}{path}{timestamp}{access_token}{shop_id}"


def sign(base_string: str, partner_key: str) -> str:
    """HMAC-SHA256（key 是 partner_key），输出小写十六进制。"""
    return hmac.new(partner_key.encode("utf-8"), base_string.encode("utf-8"),
                    hashlib.sha256).hexdigest()


# ---- 适配器 -------------------------------------------------------------------

class ShopeeAdapter(CommerceAdapter):
    """Shopee 查单。店铺由 `SHOPEE_SHOP_ID` 定（契约 §D.2），`account` 只是给 repr 看的标识。"""

    platform = PLATFORM
    status_rules = _RULES

    def __init__(self, *, transport=None, account: str = "",
                 clock: Callable[[], float] | None = None) -> None:
        super().__init__(transport=transport, account=account)
        # clock 可注入 —— 签名串里有 timestamp，不注入的话 golden 用例就没法写。
        self._clock = clock if callable(clock) else time.time

    def build_query_request(self, order_id: str) -> QueryRequest:
        partner_id = read_credential("SHOPEE_PARTNER_ID", platform=self.platform,
                                     purpose="Open Platform 的 partner_id")
        partner_key = read_credential("SHOPEE_PARTNER_KEY", platform=self.platform,
                                      purpose="Open Platform 的 partner_key（签名的 HMAC key）")
        token = read_credential("SHOPEE_ACCESS_TOKEN", platform=self.platform,
                                purpose="店铺授权的 access_token（4 小时有效）")
        shop_id = read_credential("SHOPEE_SHOP_ID", platform=self.platform,
                                  purpose="店铺的 shop_id")
        timestamp = str(int(self._clock()))
        params = {
            "partner_id": partner_id,
            "timestamp": timestamp,
            "access_token": token,
            "shop_id": shop_id,
            "sign": sign(sign_base_string(partner_id, ORDER_DETAIL_PATH, timestamp, token,
                                          shop_id), partner_key),
            "order_sn_list": str(order_id),
            # total_amount 不在默认返回字段里，要显式点名（response_optional_fields 的说明）。
            "response_optional_fields": "total_amount",
        }
        return QueryRequest(
            method="GET",
            url=f"{API_HOST}{ORDER_DETAIL_PATH}?{urllib.parse.urlencode(params)}",
        )

    def parse_order(self, payload: dict) -> RawOrder:
        # 信封：error 为空才算成功；出错时 HTTP 码可能仍是 200。
        error = payload.get("error") or ""
        if error:
            message = str(payload.get("message", ""))
            if error == "error_not_found":
                raise KeyError(f"{self.platform} 里没有订单（error_not_found：{message}）")
            raise CommerceError(self.platform, 200, str(error), message)
        response = payload.get("response")
        orders = response.get("order_list") if isinstance(response, dict) else None
        if orders is not None and not isinstance(orders, list):
            raise CommerceError(self.platform, 200, "BAD_SHAPE",
                                f"response.order_list 不是数组，是 {type(orders).__name__}")
        if not orders:
            raise KeyError(f"{self.platform} 里没有订单（error 为空，但 response.order_list 为空）")
        order = orders[0]
        if not isinstance(order, dict) or order.get("order_sn") in (None, ""):
            # 不让它以 KeyError 冒出去 —— 那会被调用方读成「订单不存在」。
            raise CommerceError(self.platform, 200, "BAD_SHAPE", "order_list[0] 缺 order_sn")
        return RawOrder(
            order_id=order["order_sn"],
            status_payload=order,
            # total_amount 文档类型是 float，原样交给 normalize_amount（它用 repr 保精度）。
            amount=order.get("total_amount"),
            # update_time 是 epoch 秒，原样交出去。
            updated_at=order.get("update_time"),
        )

    def read_error(self, response: HttpResponse) -> tuple[str, str]:
        try:
            body = json.loads(response.body)
        except (ValueError, UnicodeDecodeError):
            return "", response.text()[:500]
        if not isinstance(body, dict):
            return "", response.text()[:500]
        return str(body.get("error", "")), str(body.get("message", ""))
